pipeline {
    agent any
    stages {
        stage('Node Info') {
            steps {
                sh 'whoami'
                sh 'pwd'
                sh 'ls -la /'
                sh 'ls -la /var/run || echo "No /var/run"'
            }
        }
    }
}
