pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo "Checkout stage - simulando git"
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "Build Docker Image stage - simulando docker build"
            }
        }

        stage('Push to Docker Hub') {
            steps {
                echo "Push to Docker Hub stage - simulando docker push"
            }
        }
    }
}
